### ISSUE TITLE
Some settings need to be saved before trigger the Preview

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#269]
by @Terminator-Barbapapa 

> Add a message to the top of the preview when the user changed settings, letting them know they should save their settings to update the preview. In time we could move to instantly saving via AJAX and reloading the preview. But I think that can cause a whole new set of problems as you might not want everything to save instantly (like document number format for instance).

**Comment by alexmigf** [comment]
Fixed here: 1f1febf500e273ee0d79c2ed4f016076fc420fd4 and cdeb0ea3282592fbe0737a53127b306e4f8a73d3

**Comment by alexmigf** [comment]
Someone could also test this?

@wpovernight/plugin-devs

**Comment by dpeyou** [comment]
@alexmigf 
![Screenshot_2022-01-10_11-52-08](https://user-images.githubusercontent.com/74280840/148805877-e4477ed4-34a4-45a7-a533-0f45c6ab34e3.png)

**Comment by dpeyou** [comment]
I noticed before, that a change in logo height used to be shown in the preview. Now changing this same setting shows the message above.

**Comment by Spreeuw** [comment]
I think saving the settings shouldn't be required at all for the preview (that's what it's a live preview for, after all!).
@alexmigf is there a specific situation that requires saving?

**Comment by Spreeuw** [comment]
- Changing the logo image does not seem to trigger a refresh
- Display phone number does trigger a refresh but doesn't appear to have any effect - I think this has to do with how checkboxes are processed (and whether it was checked or not when the page was loaded?)
- Display invoice date (setting to 'no') triggers a refresh but no change... 
- Changing the invoice number format doesn't change the format (understandably from the non-preview context, but in the preview we should probably update it, while making sure it doesn't overwrite the old format).
- Changing the selected document refreshes but still shows the invoice

**Comment by alexmigf** [comment]
> - Changing the logo image does not seem to trigger a refresh

Fixed here: d890fef9e2f9ba57ae1fb8cc7b342214649e5966

> - Display phone number does trigger a refresh but doesn't appear to have any effect - I think this has to do with how checkboxes are processed (and whether it was checked or not when the page was loaded?)

It's working for me.

> - Display invoice date (setting to 'no') triggers a refresh but no change... 

Fixed here: fe1082aef5d904d4640de2917d39adeb38ca393b

> - Changing the invoice number format doesn't change the format (understandably from the non-preview context, but in the preview we should probably update it, while making sure it doesn't overwrite the old format).

Done here: b1cbe96749bae2545d88d018f34e3a87b986e07d

**Comment by Spreeuw** [comment]
> > * Display phone number does trigger a refresh but doesn't appear to have any effect - I think this has to do with how checkboxes are processed (and whether it was checked or not when the page was loaded?)
> 
> It's working for me.

Still not working for me, and I have this issue with the email address too. Like I said, it has to do with whether or not it was checked when the page was loaded. Unchecking a checkbox (that was checked before the page loaded) never seems to have an effect, while checking a checked checkbox DOES have an effect.

**Comment by alexmigf** [comment]
> Still not working for me, and I have this issue with the email address too. Like I said, it has to do with whether or not it was checked when the page was loaded. Unchecking a checkbox (that was checked before the page loaded) never seems to have an effect, while checking a checked checkbox DOES have an effect.

Fixed here: 4a9cf4001e4229cb4a1fa1b52d13271524942b09

**Comment by Spreeuw** [comment]
this doesn't appear to be used, is it?
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/4a9cf4001e4229cb4a1fa1b52d13271524942b09/assets/js/admin-script.js#L340-L353

I also see a lot of this:

https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/4a9cf4001e4229cb4a1fa1b52d13271524942b09/assets/js/admin-script.js#L117

But all of them are only using the long duration, which is a bit besides the point.
The above example is actually one where you would want to fire the request immediately upon paste (in which case you usually don't have to expect any new input), so:
```js
 let duration  = event.type == 'keyup' ? 1000 : 0; 
```

Others however only have `click` for example, in which case I don't even see a point in setting a delay at all (although duration `0` is better than not using `setTimeout`!):
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/4a9cf4001e4229cb4a1fa1b52d13271524942b09/assets/js/admin-script.js#L127

Why is this 8 seconds?
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/4a9cf4001e4229cb4a1fa1b52d13271524942b09/assets/js/admin-script.js#L137

I think that should be immediately after the logo is set?

**Comment by alexmigf** [comment]
> I think that should be immediately after the logo is set? If I read the code correctly it's currently counting on the user not taking more than 8 seconds to upload their logo and set it? The refresh should be triggered after the logo is set, and immediately.

Fixed here: ef9e16055f8a93b8fb464f0d18929047c05d4757

**Comment by Spreeuw** [comment]
> Fixed here: [ef9e160](https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/commit/ef9e16055f8a93b8fb464f0d18929047c05d4757)

I think it would be more simple/elegent to add a custom trigger here:
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/26820223ee88a3c2bfb547f83c7103d092fbb04e/assets/js/media-upload.js#L63

**Comment by alexmigf** [comment]
> I think it would be more simple/elegent to add a custom trigger here:

Yeah, haven't thought about that, good idea! I will implement that.

**Comment by alexmigf** [comment]
Implemented here: 7b564b38972dc7fa5d017b367ecaa81af68a5bda

**Comment by Spreeuw** [comment]
https://github.com/wpovernight/woocommerce-pdf-invoices-packing-slips/blob/7b564b38972dc7fa5d017b367ecaa81af68a5bda/assets/js/media-upload.js#L65-L66

technically, this could be other media upload too - not right now, but I would still name it more generically

**Comment by Spreeuw** [comment]
Made a few extra tweaks in 26b01d0a1e9e15622a89e2e99965304a1f1f132f
