### ISSUE TITLE
Searching for order odd behaviour

### ISSUE THREAD

**Issue by alexmigf** [wpovernight/woocommerce-pdf-invoices-packing-slips#270]
by @dpeyou 

> Odd behavior:
    - Search order 454 (found)
    - Change anything -- force preview to change
    - Preview goes back to the latest order (order 429) instead of remaining on #454 that I searched for.

**Comment by alexmigf** [comment]
Fixed here: 1bc35691e832720370da5062ed296a7824299ba0

Can you test @dpeyou ?

**Comment by dpeyou** [comment]
Latest order = **429**, searched order = **454**
- If I change the template or change the values of `Extended currency symbol support` or `Enable font subsetting` the preview is now refreshed with 454.
- If I change `logo height`, `test mode` value, `paper size`, I get this:
![Screenshot_2022-01-06_11-25-07](https://user-images.githubusercontent.com/74280840/148416279-ec29fe57-99e0-4620-a3b1-8f14f3615093.png)
- On page refresh: **454** remains.
- On tab switch: goes back to **429**.

**Comment by alexmigf** [comment]
@dpeyou I think it's the normal behavior.

**Obs:** You should pull the branch to get the last changes.

**Comment by dpeyou** [comment]
@alexmigf I did `$git pull` & made sure all the changes from this commit were present. :)

**Comment by alexmigf** [comment]
Hum, in that case probably you need to clear the browser cache because that notice should had more width and centered.

**Comment by dpeyou** [comment]
@alexmigf are we still on pdf-preview or am I mistaken? The notice remains the same in incognito mode & different browser.

**Comment by alexmigf** [comment]
Can you show me your branch last commit?

**Comment by dpeyou** [comment]
@alexmigf another odd thing?
![test3](https://user-images.githubusercontent.com/74280840/148820823-cf1bc449-8cae-4c7d-9270-0747e36c0e09.gif)

- Search order number in search by number 
- After the result, whether an order was found or not -> Switch to latest order -> no change, latest order not reloaded
- Enter letters in the search by number field -> last viewed order is loaded

**Comment by alexmigf** [comment]
@dpeyou fixed here 0f828f89d88722808b0640d2d4e60081717b41b1, can you do another test?

**Comment by dpeyou** [comment]
@alexmigf success! Now the latest order appears to always be loaded on click.

**Comment by dpeyou** [comment]
@alexmigf this still happens, not sure if it matters:

- Search order number in search by number (for example: "22")
- If no result (order number not found!) -> Enter letters in the search by number field (for example: "22g") -> latest order is loaded

**Comment by alexmigf** [comment]
Fixed here: 438ec81bc783491f1bbea870929edd044db835a4

**Comment by dpeyou** [comment]
@alexmigf the issue in my last comment was fixed:
![Screenshot_2022-01-17_09-27-49](https://user-images.githubusercontent.com/74280840/149789115-b6733db7-75d3-4512-a68b-97f0442ebf8e.png)


**More potential odd behavior:**
Last order is **#467**, status = proposal requested (disabled in settings)
- Search for other order (3rd option). Click order that is found.
- Click latest order: latest order not loaded, no change in the currently loaded order.

![test5](https://user-images.githubusercontent.com/74280840/149789040-1ce8616d-befc-41ad-ac37-413d3a8180a5.gif)

**Comment by alexmigf** [comment]
Fixed here: ae13adfa821fca237057623495801642fc542795

**Comment by dpeyou** [comment]
@alexmigf 
![Screenshot_2022-01-17_11-16-02](https://user-images.githubusercontent.com/74280840/149804906-14486d16-bb7c-463a-9422-2d2c94181aa1.png)
![Screenshot_2022-01-17_11-14-53](https://user-images.githubusercontent.com/74280840/149804912-33ac7b5d-a1e1-48aa-a105-5f0707fd2376.png)

This is showing the latest document instead of an error message:
![Screenshot_2022-01-17_11-17-34](https://user-images.githubusercontent.com/74280840/149805165-f7e62a09-6d81-4a9c-a1c9-4fdf602d8fbb.png)

If I disable the Invoice document, the expected error returns:
![Screenshot_2022-01-17_11-18-10](https://user-images.githubusercontent.com/74280840/149805247-8db2efb7-0cc1-436a-820a-8f870af4d3f5.png)

**Comment by alexmigf** [comment]
@dpeyou seems fine to me.
